baseURL = 'https://taishiyu.github.io/pianezzo/'
defaultContentLanguage = 'en-us'
title = 'Il Giardino Nascosto'
theme = 'ananke'

[[menus.main]]
    name = 'Land'
    url = '/land/'
    weight = 10

[[menus.main]]
    name = 'Seasons'
    url = '/seasons/'
    weight = 20

[[menus.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 30

[[menus.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 40
