baseURL = 'https://taishiyu.github.io/pianezzo/'
defaultContentLanguage = 'en-us'
title = 'Il Giardino Nascosto'
theme = 'ananke'

[[menus.main]]
    name = 'Land'
    url = '/land/'
    weight = 1

[[menus.main]]
    name = 'Spring'
    url = '/spring/'
    weight = 2

[[menus.main]]
    name = 'Summer'
    url = '/summer/'
    weight = 3

[[menus.main]]
    name = 'Autumn'
    url = '/autumn/'
    weight = 4

[[menus.main]]
    name = 'Winter'
    url = '/winter/'
    weight = 5
